"""fix_event_status_and_timezones

Revision ID: 2223feab43ec
Revises: 8ad04c90079f
Create Date: 2026-08-02 11:23:27.478602

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2223feab43ec"
down_revision: str | Sequence[str] | None = "8ad04c90079f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "CANCELLED", name="event_status_enum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "status")
    # ### end Alembic commands ###
