"""add_timezone_to_datetimes2

Revision ID: 5138dd02923b
Revises: f28441bb075e
Create Date: 2026-08-02 10:18:09.782825

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5138dd02923b"
down_revision: str | Sequence[str] | None = "f28441bb075e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
