"""init

Revision ID: 8f12e66fdc65
Revises:
Create Date: 2026-08-02 09:25:45.409719

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8f12e66fdc65"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
